### ISSUE TITLE
Olib and go2 FWI transport settings use different variables

### ISSUE THREAD

**Issue by sandersch** [ondreian/Olib#13]
Tillmen recently updated the `;go2` script to support a FWI trinket setting. Unfortunately he choose to use `UserVars.mapdb_fwi_trinket` while this library uses `Vars.teleporter` for the the transporter setting.

What do you think about using `Vars.teleporter` if it is set but trying `UserVars.mapdb_fwi_trinket` as a fallback?

**Comment by ondreian** [comment]
I have no problems just mapping to the `;go2` setting to maintain continuity. If this is the case though a few of the methods could be slated for removal.
